// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      //case TargetPlatform.iOS:
        return ios;
     // case TargetPlatform.macOS:
        return macos;
     // case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
     // case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvZuQPtzE-vHfu9GCqUZpEQp8MkLRDLlo',
    appId: '1:969244837835:web:e3e8a9176e58fdbe85184e',
    messagingSenderId: '969244837835',
    projectId: 'keja-aa0a8',
    authDomain: 'keja-aa0a8.firebaseapp.com',
    databaseURL: 'https://keja-aa0a8-default-rtdb.firebaseio.com',
    storageBucket: 'keja-aa0a8.appspot.com',
    measurementId: 'G-Y6BECPEJET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkav7rDOX3wgKmsxjDiCKZdez5_TUr0Bw',
    appId: '1:969244837835:android:997d7654f1c2110f85184e',
    messagingSenderId: '969244837835',
    projectId: 'keja-aa0a8',
    databaseURL: 'https://keja-aa0a8-default-rtdb.firebaseio.com',
    storageBucket: 'keja-aa0a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ntDOTLh6kXAC3TtF1d8ZY2iOAQ0RZbk',
    appId: '1:969244837835:ios:42086e26153bed3c85184e',
    messagingSenderId: '969244837835',
    projectId: 'keja-aa0a8',
    databaseURL: 'https://keja-aa0a8-default-rtdb.firebaseio.com',
    storageBucket: 'keja-aa0a8.appspot.com',
    iosClientId: '969244837835-r15e2a3n32h5mt6f5v2jtqdlgniu8qjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ntDOTLh6kXAC3TtF1d8ZY2iOAQ0RZbk',
    appId: '1:969244837835:ios:42086e26153bed3c85184e',
    messagingSenderId: '969244837835',
    projectId: 'keja-aa0a8',
    databaseURL: 'https://keja-aa0a8-default-rtdb.firebaseio.com',
    storageBucket: 'keja-aa0a8.appspot.com',
    iosClientId: '969244837835-r15e2a3n32h5mt6f5v2jtqdlgniu8qjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeja',
  );
}
